### ISSUE TITLE
Usage and adaptation of your script

### ISSUE THREAD

**Issue by selfire1** [jgclark/BibleGateway-to-Markdown#3]
Hi! 👋 Your script has been incredibly useful to me to import Scripture into [Obsidian](obsidian.md).

I made some changes and paired it with a bash-script to import easily into Obsidian. I would love to publish my script with your adapted version to make it easy for non-programmy folks to use the Bible in Obsidian. I published the code [in this repository](https://github.com/selfire1/BibleGateway-to-Obsidian/blob/main/README.md).

Please let me know if this usage and adaptation of your script is okay with you or if you would like me to further attribute / not use it.

**Comment by jgclark** [comment]
Hi, @selfire1, this is a most interesting development (pun intended).
This is the beauty of open source tools, and the Unix principle of being able to build bigger tools from collections of smaller ones.

I'm happy for anyone to be using my scripts -- that's why I published them -- but naturally it's a different story whether BibleGateway would be happy to have the whole of a Bible text gathered in this way. Personally, if I already have purchased a paper and/or digital copy of that Bible version, I'm fine with gathering portions of it for private use. (We could always use an OCR system; this is just quicker.)

Out of interest is your idea to change verse numbers to H6 so that you can link to any individual verse in Obsidian?  I'm also a sometimes user of Obsidian, and I'm part of a Discord group there and for my chosen task/note/calendar manager, [NotePlan](https://noteplan/co) where I help develop scripts to help it interoperate with other systems, including Obsidian.

**Comment by selfire1** [comment]
Hi @jgclark, thanks for the permission (and the ⭐).

Yeah, copyrights of translations and usage of BibleGateway is the tricky bit. To be "above reproach" I changed the default version to the royalty-free World English Bible. In my understanding using the script doesn't violate [BibleGateways's terms of usage](https://support.biblegateway.com/hc/en-us/articles/360001398808-How-do-I-get-permission-to-use-or-reprint-Bible-content-from-Bible-Gateway-?) as long as it doesn't violate copyright claims. Being "above reproach" in the usage is important for me though.

Yeah, I've changed the verse numbers to H6 to allow simple referencing and added navigation in the files.

**Comment by jgclark** [comment]
Thanks.

I see you're using a forked version of the script, which is of course fine, but given that BG will continue to change their (undocumented) HTML format, it may not be ideal. I've not looked in detail to see how you've changed it, but I'm happy to take Feature requests (or PRs!) to make improvements, so that you can then use my script directly. That way when I respond to changes at BG, you won't have to rework them as well.

So, do add a request an option for verse numbers to be H6 (or H5 or whatever) ...
